### ISSUE TITLE
Typo in Turkish

### ISSUE THREAD

**Issue by bajosiaa** [MicrosoftDocs/visualstudio-docs.tr-tr#10]
renk teonu > renk tonu

**Comment by srvbpigh** [comment]
Merhaba @bajosiaa:

Şirket içi işleme ve mühendislik işlem hattımızı değiştiriyoruz. Ne yazık ki bu, geri bildiriminizin işlenmesinde gecikmelere yol açıyor.

Makalelerimize sağladığınız katkıları gerçekten takdir ediyor, desteklerinizin ve anlayışınızın devam etmesini diliyoruz.
