### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by p1v0t** [MicrosoftDocs/visualstudio-docs.tr-tr#2]
Google Test Primer link at last paragraph of the article is broken.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [Visual Studio'da C++ için Google Test kullanma](https://docs.microsoft.com/tr-tr/visualstudio/test/how-to-use-google-test-for-cpp)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/blob/live/docs/test/how-to-use-google-test-for-cpp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by LisandroSu** [comment]
Hello, @p1v0t , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by p1v0t** [comment]
Ohh, thank you for care @LisandroSu .

**Comment by LisandroSu** [comment]
Hello @p1v0t 

Thank you for your feedback. The link is working now.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
